import type { Metadata } from 'next'
import { Work_Sans, Fugaz_One } from 'next/font/google'
import './globals.scss'

import { Navigator } from 'common'

const fugaz_one = Fugaz_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-fugaz-one'
})

const work_sans = Work_Sans({
  subsets: ['latin'],
  weight: ['300', '500', '700'],
  variable: '--font-work-sans'
})

export const metadata: Metadata = {
  title: 'Gustavo Blog',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${work_sans.variable} ${fugaz_one.variable}`}
    >
      <body>
        <Navigator />
        {children}
      </body>
    </html>
  )
}
